.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\"
.\" Copyright 1989 AT&T
.\" Copyright (c) 2003, Sun Microsystems, Inc. All Rights Reserved
.\"
.Dd February 1, 2003
.Dt SEMCTL 2
.Os
.Sh NAME
.Nm semctl
.Nd semaphore control operations
.Sh SYNOPSIS
.In sys/types.h
.In sys/ipc.h
.In sys/sem.h
.Ft int
.Fn semctl "int semid" "int semnum" "int cmd" "..."
.Sh DESCRIPTION
The
.Fn semctl
function provides a variety of semaphore control operations
as specified by
.Fa cmd .
The fourth argument is optional, depending upon the
operation requested.
If required, it is of type
.Vt "union semun" ,
which must be explicitly declared by the application program:
.Bd -literal -offset indent
union semun {
	int		 val;
	struct semid_ds	*buf;
	ushort_t	*array;
} arg;
.Ed
.Pp
The permission required for a semaphore operation is given as
.Brq Va token ,
where
.Va token
is the type of permission needed.
The types of permission are interpreted as follows:
.Bd -literal -offset indent
00400	READ by user
00200	ALTER by user
00040	READ by group
00020	ALTER by group
00004	READ by others
00002	ALTER by others
.Ed
.Pp
See the
.Sy Semaphore Operation Permissions
subsection of
.Xr Intro 2
for more information.
The following semaphore operations as specified by
.Fa cmd
are executed with respect to the semaphore specified by
.Fa semid
and
.Fa semnum .
.Bl -tag -width "GETNCNT"
.It Dv GETVAL
Return the value of  semval
.Po see Xr Intro 2 Pc . Brq Dv READ
.It Dv SETVAL
Set the value of
.Va semval
to
.Va arg.val .
.Brq Dv ALTER .
When this command is successfully executed, the
.Va semadj
value corresponding to the specified semaphore in all processes is cleared.
.It Dv GETPID
Return the value of
.Po Vt int Pc Ns sempid . Brq Dv READ
.It Dv GETNCNT
Return the value of
.Va semncnt . Brq Dv READ
.It Dv GETZCNT
Return the value of
.Va semzcnt . Brq Dv READ
.El
.Pp
The following operations return and set, respectively, every
.Va semval
in the set of semaphores:
.Bl -tag -width "GETALL"
.It Dv GETALL
Place
.Va semval Ns s
into the array pointed to by
.Va arg.array . Brq Dv READ
.It Dv SETALL
Set
.Va semval Ns s
according to the array pointed to by
.Va arg.array . Brq Dv ALTER .
When this cmd is successfully executed, the
.Va semadj
values corresponding to each specified semaphore in all processes are cleared.
.El
.Pp
The following operations are also available:
.Bl -tag -width "IPC_STAT"
.It Dv IPC_STAT
Place the current value of each member of the data structure associated with
.Fa semid
into the structure pointed to by
.Va arg.buf .
The contents
of this structure are defined in
.Xr Intro 2 . Brq Dv READ
.It Dv IPC_SET
Set the value of the following members of the data structure associated with
.Fa semid
to the corresponding value found in the structure pointed to by
.Va arg.buf :
.Bd -literal -offset indent
sem_perm.uid
sem_perm.gid
sem_perm.mode	/* access permission bits only */
.Ed
.Pp
This command can be executed only by a process that has either the
.Brq Dv PRIV_IPC_OWNER
privilege or an effective user ID equal to the
value of
.Va msg_perm.cuid
or
.Va msg_perm.uid
in the data structure
associated with
.Va msqid .
Only a process with the
.Brq Dv PRIV_SYS_IPC_CONFIG
privilege can raise the value of
.Va msg_qbytes .
.It Dv IPC_RMID
Remove the semaphore identifier specified by
.Fa semid
from the system and destroy the set of semaphores and data structure associated
with it.
This command can be executed only by a process that has the
.Brq Dv PRIV_IPC_OWNER
privilege or an effective user ID equal to the value of
.Va sem_perm.cuid
or
.Va sem_perm.uid
in the data structure associated with
.Va semid .
.El
.Sh RETURN VALUES
Upon successful completion, the value returned depends on
.Fa cmd
as follows:
.Pp
.Bl -tag -width "GETNCNT" -compact
.It Dv GETVAL
The value of
.Va semval .
.It Dv GETPID
The value of
.Po Vt int Pc Ns sempid .
.It Dv GETNCNT
The value of
.Va semncnt .
.It Dv GETZCNT
The value of
.Va semzcnt .
.El
.Pp
All other successful completions return the value 0; otherwise the value -1 is
returned and the global variable
.Va errno
is set to indicate the error.
.Sh ERRORS
The
.Fn semctl
function will fail if:
.Bl -tag -width Er
.It Bq Er EACCES
Operation permission is denied to the calling process
.Pq see Xr Intro 2 .
.It Bq Er EFAULT
The source or target is not a valid address in the user process.
.It Bq Er EINVAL
The
.Fa semid
argument is not a valid semaphore identifier; the
.Va semnum
argument is less than 0 or greater than
.Ql sem_nsems -1 ;
or the
.Va cmd
argument is not a valid command or is
.Dv IPC_SET
and
.Va sem_perm.uid
or
.Va sem_perm.gid
is not valid.
.It Bq Er EPERM
The
.Fa cmd
argument is equal to
.Dv IPC_RMID
or
.Dv IPC_SET ,
the effective user ID of the calling process is not equal to the value of
.Va sem_perm.cuid
or
.Va sem_perm.uid
in the data structure associated with
.Va semid ,
and
.Brq Dv PRIV_IPC_OWNER
is not asserted in the effective set of the calling process.
.It Bq Er EOVERFLOW
The
.Fa cmd
argument is
.Dv IPC_STAT
and
.Va uid
or
.Va gid
is too large to be stored in the structure pointed to by
.Va arg.buf .
.It Bq Er ERANGE
The
.Fa cmd
argument is
.Dv SETVAL
or
.Dv SETALL
and the value to which
.Fa semval
is to be set is greater than the system imposed maximum.
.El
.Sh INTERFACE STABILITY
.Sy Standard
.Sh SEE ALSO
.Xr ipcs 1 ,
.Xr Intro 2 ,
.Xr semget 2 ,
.Xr semop 2 ,
.Xr attributes 5 ,
.Xr privileges 5 ,
.Xr standards 5
